rebar: remove copies of alcove from search path
To avoid rebuilding the alcove binary on each invocation, the
rebar.config.script only runs the configuration tests if the binary does
not exist.

A freshly checked out git repo will fail during the port compilation
step if another version of alcove is in the search path because the
checks will not run:

~~~
/tmp/x/prx/_build/default/lib/alcove/c_src/sys/setns.c:30:12: error: static declaration of ‘setns’ follows non-static declaration
 static int setns(int fd, int nstype);
            ^
In file included from /usr/include/sched.h:43:0,
                 from /tmp/x/prx/_build/default/lib/alcove/c_src/sys/setns.c:17:
/usr/include/x86_64-linux-gnu/bits/sched.h:91:12: note: previous declaration of ‘setns’ was here
 extern int setns (int __fd, int __nstype) __THROW;
            ^
/tmp/x/prx/_build/default/lib/alcove/c_src/sys/clone.c:21:9: note: #pragma message: Support for namespaces using clone(2) enabled
 #pragma message "Support for namespaces using clone(2) enabled"
         ^
Makefile:59: recipe for target '/tmp/x/prx/_build/default/lib/alcove/c_src/../priv/alcove' failed
make: *** [/tmp/x/prx/_build/default/lib/alcove/c_src/../priv/alcove] Error 1
make: Leaving directory '/tmp/x/prx/_build/default/lib/alcove/c_src'
===> Hook for compile failed!
~~~

Delete copies of alcove from the search path. It is possible compilation
may still fail if multiple, shadowed copies of alcove are in the search
path.

Should fix: https://github.com/msantos/prx/issues/2